version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/cafeguidebook/
file_exists_behavior: OVERWRITE
permissions:
  - object: /home/ec2-user/cafeguidebook/
    pattern: "*"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
hooks:
  AfterInstall:
    - location: /start.sh
      timeout: 180
